import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Box,
  Paper,
  Typography,
  Alert,
  Snackbar,
  CircularProgress,
  Button
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, LockOutlined as LockIcon } from '@mui/icons-material';
import UserLayout from '../../../components/UserLayout';
import TransactionForm from '../../../components/TransactionForm';
import TransactionService from '../../../services/transaction.service';

const TransactionEdit = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [transaction, setTransaction] = useState(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [openSnackbar, setOpenSnackbar] = useState(false);

  // Check if a transaction is an automatic tax expense (should be protected)
  const isAutomaticTaxExpense = (transaction) => {
    return (
      transaction && 
      transaction.category === 'Taxes' && 
      transaction.type === 'expense' && 
      transaction.tags && 
      Array.isArray(transaction.tags) && 
      (transaction.tags.includes('#automatic') || transaction.tags.includes('#tax'))
    );
  };

  useEffect(() => {
    const fetchTransaction = async () => {
      try {
        setLoading(true);
        const data = await TransactionService.getTransactionById(id);
        
        // Convert tags array to comma-separated string for the form
        if (data.tags && Array.isArray(data.tags)) {
          data.tags = data.tags.join(', ');
        } else {
          data.tags = '';
        }
        
        setTransaction(data);

        // If it's an automatic tax expense, show warning
        if (isAutomaticTaxExpense(data)) {
          setError('Automatic tax expense entries cannot be edited. These entries are managed by the system.');
        }
      } catch (err) {
        setError(err.message || 'Failed to fetch transaction details');
      } finally {
        setLoading(false);
      }
    };

    fetchTransaction();
  }, [id]);

  const handleSubmit = async (values, { setSubmitting }) => {
    try {
      // Block submission if it's an automatic tax expense
      if (isAutomaticTaxExpense(transaction)) {
        setError('Automatic tax expense entries cannot be edited.');
        setSubmitting(false);
        return;
      }

      setIsSubmitting(true);
      setError('');

      // Process tags if provided - convert from string to array
      let processedValues = { ...values };
      if (values.tags) {
        processedValues.tags = values.tags.split(',')
          .map(tag => {
            tag = tag.trim();
            return tag.startsWith('#') ? tag : `#${tag}`;
          });
      } else {
        processedValues.tags = [];
      }

      await TransactionService.updateTransaction(id, processedValues);
      setOpenSnackbar(true);
      
      // Navigate back after success
      setTimeout(() => {
        navigate('/transactions');
      }, 1500);
    } catch (err) {
      setError(err.message || 'Error updating transaction');
    } finally {
      setIsSubmitting(false);
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <UserLayout title="Edit Transaction">
        <Box sx={{ display: 'flex', justifyContent: 'center', mt: 4 }}>
          <CircularProgress />
        </Box>
      </UserLayout>
    );
  }

  if (!transaction) {
    return (
      <UserLayout title="Edit Transaction">
        <Alert severity="error" sx={{ mt: 2 }}>
          Transaction not found or you don't have permission to edit it.
        </Alert>
      </UserLayout>
    );
  }

  // If it's an automatic tax expense, show a different UI
  if (isAutomaticTaxExpense(transaction)) {
    return (
      <UserLayout title="Protected Transaction">
        <Box sx={{ maxWidth: 800, mx: 'auto', my: 2 }}>
          <Paper sx={{ p: 3 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
              <LockIcon color="primary" sx={{ mr: 1, fontSize: 30 }} />
              <Typography variant="h5" component="div">
                Protected Transaction
              </Typography>
            </Box>
            
            <Alert severity="info" sx={{ mb: 3 }}>
              This is an automatic tax expense entry generated by the system. It cannot be manually edited or deleted as it is linked to your tax calculations.
              <br /><br />
              To change the tax amount, please adjust your tax settings in the <strong>Manage Taxes</strong> section.
            </Alert>
            
            <Typography variant="body1" gutterBottom sx={{ mb: 2 }}>
              <strong>Transaction Details:</strong>
            </Typography>
            
            <Box sx={{ ml: 2, mb: 3 }}>
              <Typography variant="body1" gutterBottom>
                <strong>Date:</strong> {new Date(transaction.date).toLocaleDateString()}
              </Typography>
              <Typography variant="body1" gutterBottom>
                <strong>Category:</strong> {transaction.category}
              </Typography>
              <Typography variant="body1" gutterBottom>
                <strong>Amount:</strong> ${Number(transaction.amount).toFixed(2)}
              </Typography>
              <Typography variant="body1" gutterBottom>
                <strong>Description:</strong> {transaction.description}
              </Typography>
            </Box>
            
            <Button
              variant="contained"
              startIcon={<ArrowBackIcon />}
              onClick={() => navigate('/transactions')}
            >
              Back to Transactions
            </Button>
          </Paper>
        </Box>
      </UserLayout>
    );
  }

  return (
    <UserLayout title="Edit Transaction">
      <Box sx={{ maxWidth: 800, mx: 'auto', my: 2 }}>
        <Paper sx={{ p: 3 }}>
          <Typography variant="h5" gutterBottom>
            Edit Transaction
          </Typography>
          
          {error && (
            <Alert severity="error" sx={{ mb: 2 }}>
              {error}
            </Alert>
          )}
          
          <TransactionForm
            initialValues={transaction}
            onSubmit={handleSubmit}
            isSubmitting={isSubmitting}
            buttonText="Update Transaction"
          />
        </Paper>
      </Box>
      
      <Snackbar
        open={openSnackbar}
        autoHideDuration={3000}
        onClose={() => setOpenSnackbar(false)}
      >
        <Alert severity="success">
          Transaction updated successfully!
        </Alert>
      </Snackbar>
    </UserLayout>
  );
};

export default TransactionEdit; 